# Generated by Django 4.0.6 on 2022-07-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
            ],
        ),

        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('institution', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.faculty'))
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('direction', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.direction')),
            ],
        ),

    ]
