# Generated by Django 4.0.6 on 2022-07-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='book_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
