# Generated by Django 4.0.6 on 2022-07-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_list_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.institution'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
